## name: evergarden fall skye
## author: comfysage
## license: GPL-3.0
## blurb: a comfy colorscheme for cozy morning coding

[colors.primary]
background = "#101010"
foreground = "#b0b0b0"
dim_foreground = "#777777"
bright_foreground = "#b0b0b0"

[colors.cursor]
text = "#101010"
cursor = "#0058d0"

[colors.vi_mode_cursor]
text = "#101010"
cursor = "#0058d0"

[colors.search.matches]
foreground = "#ff7676"
background = "#181818"

[colors.search.focused_match]
foreground = "#101010"
background = "#ff7676"

[colors.footer_bar]
foreground = "#b0b0b0"
background = "#181818"

[colors.hints.start]
foreground = "#101010"
background = "#d9ba73"

[colors.hints.end]
foreground = "#101010"
background = "#b0b0b0"

[colors.selection]
text = "#b0b0b0"
background = "#181818"

[colors.normal]
black = "#101010"
red = "#ff7676"
green = "#86cd82"
yellow = "#d9ba73"
blue = "#8ebeec"
magenta = "#d9ba73"
cyan = "#0058d0"
white = "#b0b0b0"

[colors.bright]
black = "#181818"
red = "#ff7676"
green = "#86cd82"
yellow = "#d9ba73"
blue = "#8ebeec"
magenta = "#d9ba73"
cyan = "#0058d0"
white = "#b0b0b0"

[colors.dim]
black = "#101010"
red = "#ff7676"
green = "#86cd82"
yellow = "#d9ba73"
blue = "#8ebeec"
magenta = "#d9ba73"
cyan = "#0058d0"
white = "#b0b0b0"
