accent = "#d9ba73"
cursor = "#d9ba73"
foreground = "#ffffff"
background = "#101010"
selection_foreground = "#ffffff"
selection_background = "#50585d"

color0 = "#272727"
color1 = "#ff7676"
color2 = "#86cd82"
color3 = "#d9ba73"
color4 = "#8ebeec"
color5 = "#d9ba73"
color6 = "#ffffff"
color7 = "#777777"
color8 = "#50585d"
color9 = "#ff7676"
color10 = "#8ebeec"
color11 = "#d9ba73"
color12 = "#8ebeec"
color13 = "#d9ba73"
color14 = "#0058d0"
color15 = "#b0b0b0"
